catalog.dependencies.aws-sqs=aws-sqs/aws-sqs.dependencies.txt
catalog.description=Send and receive messages over AWS SQS with request/reply using Apache Camel
catalog.name=aws-sqs-tool
catalog.routes.aws-sqs=aws-sqs/aws-sqs.camel.yaml
catalog.rules.aws-sqs=aws-sqs/aws-sqs.rules.yaml
catalog.services=aws-sqs
